export const categories = ['pathologies', 'medicaments', 'examens-paracliniques', 'examens-cliniques', 'soins-de-plaies', 'interventions', 'perinatalite-pediatrie'];

export const keyOrder = [
    // Communs & Médicaments
    'definition', 'description', 'molecules_list', 'indications', 'mode_action', 'pharmacocinetique', 'pharmacodynamie',
    'contre_indications', 'precautions', 'reactions_indesirables', 'effets_secondaires', 'interactions', 'posologie', 'presentation',
    'soins_infirmiers',

    // Pathologies
    'types', 'types_avc', 'types_ic', 'manifestations_cliniques', 'examens_diagnostiques',
    'traitements', 'surveillance', 'complications', 'complications_specifiques',

    // Examens & Interventions
    'but', 'normes', 'interpretations', 'soins_pre_op', 'surveillance_post_op', 'soins_post_op',
    'soins_infirmiers_post_op', 'signes_alerte', 'conseils_post_op', 'soins_et_precautions',
    'education_patient', 'post_op', 'soins', 'en_post_op', 'parametres_de_base', 'urgences',
    'acces_vasculaires', 'soins_fistule', 'surveillance_traitement', 'principes', 'soins_pre_transfusionnels',
    'surveillance_pendant', 'complications_rections', 'surveillance_calcium', 'soins_moignon', 'douleur'
];

export const linkMapping = [
    // === MÉDICAMENTS (Classes & Molécules) ===
    { keywords: ['antibiotique', 'antibiotiques', 'antibiothérapie', 'antibiotherapie'], target: 'Antibiotiques' },
    { keywords: ['amoxicilline', 'amoxicillin', 'amoxil', 'amoxi', 'novamoxin', 'pro-amox'], target: 'Amoxicilline' },
    { keywords: ['amoxicilline-clavulanate', 'amoxicilline clavulanate', 'clavulin', 'apo-amoxi clav'], target: 'Amoxicilline-clavulanate' },
    { keywords: ['ampicilline', 'ampicin', 'nu-ampi', 'teva-ampicillin'], target: 'Ampicilline' },
    { keywords: ['cloxacilline', 'cloxacillin', 'orbenin', 'teva-cloxacilline'], target: 'Cloxacilline' },
    { keywords: ['amikacine', 'amikin', 'gentamicine', 'garamycin', 'néomycine', 'neomycine', 'streptomycine', 'tobramycine', 'jamp-tobramycine', 'nebcin', 'teva-tobramycine', 'tobi', 'tobi podhaler'], target: 'Amikacine, Gentamicine, Néomycine, Streptomycine, Tobramycine' },
    { keywords: ['ertapénème', 'ertapeneme', 'invanz'], target: 'Ertapénème' },
    { keywords: ['imipénème-cilastatine', 'imipénème', 'imipeneme', 'cilastatine', 'primaxin', 'ran-imipenem-cilastatin'], target: 'Imipénème-cilastatine' },
    { keywords: ['méropénème', 'meropenem', 'merrem'], target: 'Méropénème' },
    { keywords: ['céfadroxil', 'cefadroxil', 'apo-cefadroxil', 'duricef', 'pro-cefadroxil', 'teva-cefadroxil', 'céfazoline', 'cefazoline', 'ancef', 'kefzol', 'céphalexine', 'cephalexine', 'apo-cephalex', 'keflex', 'teva-cephalexin'], target: 'Céfadroxil, Céfazoline, Céphalexine' },
    { keywords: ['céfoxitine', 'cefoxitine', 'mefoxin', 'cefprozil', 'apo-cefprozil', 'cefzil', 'ran-cefprozil', 'sandoz-cefprozil', 'céfuroxime', 'cefuroxime', 'apo-cefuroxime', 'auro-cefuroxime', 'ceftin', 'kefurox', 'pro-cefuroxime', 'ratio-cefuroxime', 'zinacef'], target: 'Céfoxitine, Cefprozil, Céfuroxime' },
    { keywords: ['céfixime', 'cefixime', 'auro-cefixime', 'suprax', 'céfotaxime', 'cefotaxime', 'claforan', 'ceftazidime', 'fortaz', 'ceftriaxone', 'rocephin', 'céfépime', 'cefepime', 'maxipime'], target: 'Céfixime, Céfotaxime, Ceftazidime, Ceftriaxone, Céfépime' },
    { keywords: ['ciprofloxacine', 'ciprofloxacin', 'cipro', 'ciprofloxac', 'lévofloxacine', 'levofloxacin', 'levaquin', 'moxifloxacine', 'moxifloxacin', 'avelox', 'norfloxacine', 'norfloxacin', 'noroxin', 'ofloxacine', 'ofloxacin', 'floxin'], target: 'Ciprofloxacine, Lévofloxacine, Moxifloxacine, Norfloxacine, Ofloxacine' },
    { keywords: ['azithromycine', 'azithromycin', 'zithromax', 'z-pak'], target: 'Azithromycine' },
    { keywords: ['clarithromycine', 'clarithromycin', 'biaxin', 'biaxin xl'], target: 'Clarithromycine' },
    { keywords: ['érythromycine', 'erythromycine', 'erythromycin', 'eryc', 'erythrocin', 'pce', 'erythro-es', 'ees 600', 'erypak', 'erysol', 'novo rythro', 'ilotycin'], target: 'Érythromycine' },
    { keywords: ['clindamycine', 'clindamycin', 'dalacin c', 'dalacin t', 'clinda-t', 'clindets'], target: 'Clindamycine' },
    { keywords: ['pénicilline g', 'penicilline g', 'penicilline v', 'pénicilline v', 'bicillin-la', 'bicillin', 'crystapen', 'pen vk', 'pen-vee'], target: 'Pénicilline G et Pénicilline V' },
    { keywords: ['vancomycine', 'vancomycin', 'vancocin', 'jamp-vancomycine'], target: 'Vancomycine' },
    { keywords: ['pipéracilline', 'piperacilline', 'piperacillin', 'pipracil', 'pipéracilline-tazobactam', 'piperacilline-tazobactam', 'piperacillin-tazobactam', 'tazocin'], target: 'Pipéracilline et Pipéracilline-tazobactam' },
    { keywords: ['triméthoprime-sulfaméthoxazole', 'trimethoprime-sulfamethoxazole', 'bactrim', 'septra', 'apo-sulfatrim', 'teva-trimel', 'sulfatrim'], target: 'Triméthoprime-sulfaméthoxazole' },
    { keywords: ['doxycycline', 'apo-doxy', 'doxycin', 'periostat', 'teva-doxycycline', 'vibramycin', 'vibra-tabs', 'apprilon', 'minocycline', 'apo-minocycline', 'arestin', 'minocin', 'mylan-minocycline', 'pms-minocycline', 'sandoz-minocycline', 'teva-minocycline', 'tétracycline', 'tetracycline'], target: 'Doxycycline, Minocycline, Tétracycline' },
    { keywords: ['anticholinergique', 'anticholinergiques', 'atropine'], target: 'Atropine' },
    { keywords: ['darifénacine', 'darifenacine', 'enablex'], target: 'Darifénacine' },
    { keywords: ['fésotérodine', 'fesoterodine', 'toviaz'], target: 'Fésotérodine' },
    { keywords: ['glycopyrrolate', 'robinul'], target: 'Glycopyrrolate' },
    { keywords: ['oxybutynine', 'oxybutinine', 'apo-oxybutynine', 'ditropan', 'ditropan xl', 'gelnique', 'oxytrol', 'pmsoxybutynine', 'riva-oxybutynine', 'teva-oxybutynine'], target: 'Oxybutynine' },
    { keywords: ['scopolamine', 'hyoscine', 'transderm-v', 'buscopan'], target: 'Scopolamine' },
    { keywords: ['solifénacine', 'solifenacine', 'auro-solifénacine', 'jamp-solifénacine', 'pms-solifénacine', 'ran-solifénacine', 'teva-solifénacine', 'vesicare'], target: 'Solifénacine' },
    { keywords: ['toltérodine', 'tolterodine', 'apo-toltérodine', 'detrol', 'detrol la', 'mylan-toltérodine', 'teva-toltérodine'], target: 'Toltérodine' },
    { keywords: ['trospium', 'trosec'], target: 'Trospium' },
    { keywords: ['antiasthmatique'], target: 'Antiasthmatiques' },
    { keywords: ['aminophylline', 'aminophyline', 'oxtriphylline', 'choledyl', 'théophylline', 'theophylline', 'uniphyl', 'theolair'], target: 'Aminophylline, Oxtriphylline, Théophylline' },
    { keywords: ['formotérol', 'formoterol', 'foradil', 'oxeze'], target: 'Formotérol' },
    { keywords: ['orciprénaline', 'orciprenaline', 'métaprotérénol', 'metaproterenol', 'alupent'], target: 'Orciprénaline' },
    { keywords: ['salbutamol', 'albutérol', 'albuterol', 'airomir', 'salvent', 'ventolin'], target: 'Salbutamol' },
    { keywords: ['salmétérol', 'salmeterol', 'serevent'], target: 'Salmétérol' },
    { keywords: ['terbutaline', 'bricanyl'], target: 'Terbutaline' },
    { keywords: ['vilantérol', 'vilanterol', 'breo ellipta', 'anoro ellipta', 'trelegy ellipta'], target: 'Vilantérol' },
    { keywords: ['béclométhasone', 'beclomethasone', 'qvar', 'budésonide', 'budesonide', 'pulmicort', 'nebuamp', 'ciclésonide', 'ciclesonide', 'alvesco', 'fluticasone', 'flovent', 'arnuity', 'mométasone', 'mometasone', 'asmanex'], target: 'Béclométhasone, Budésonide, Ciclésonide, Fluticasone, Mométasone' },
    { keywords: ['cortisone', 'cortone', 'hydrocortisone', 'cortef', 'solu-cortef', 'méthylprednisolone', 'methylprednisolone', 'depo-medrol', 'medrol', 'solu-medrol', 'prednisolone', 'pediapred', 'prednisone', 'apo-prednisone', 'deltasone', 'novo-prednisone', 'winpred', 'triamcinolone', 'kenalog', 'aristopan', 'bétaméthasone', 'betamethasone', 'betaject', 'celestone', 'cortiment', 'entocort', 'dexaméthasone', 'dexamethasone', 'decadron', 'dexasone'], target: 'Bétaméthasone, Budésonide, Cortisone, Dexaméthasone, Hydrocortisone, Méthylprednisolone, Prednisolone, Prednisone, Triamcinolone' },
    { keywords: ['cromolyn', 'cromoglycate', 'nalcrom', 'opticrom', 'rhinaris', 'nédocromil', 'nedocromil', 'alocril'], target: 'Cromolyn, Nédocromil' },
    { keywords: ['diurétique', 'diuretique'], target: 'Diurétiques' },
    { keywords: ['bêta-bloquant', 'beta-bloquant', 'bêtabloquant'], target: 'Antihypertenseurs' },
    { keywords: ['ieca', 'iec', 'inhibiteur de l’enzyme de conversion'], target: 'Antihypertenseurs' },
    { keywords: ['ara ii', 'ara 2', 'antagoniste récepteur de l’angiotensine'], target: 'Antihypertenseurs' },
    { keywords: ['bloqueur des canaux calciques', 'inhibiteur calcique', 'amlodipine'], target: 'Antihypertenseurs' },
    { keywords: ['aspirine', 'aas'], target: 'AAS (Aspirine)' },
    { keywords: ['anticoagulant', 'anticoagulation', 'coumadin', 'warfarine', 'héparine'], target: 'Anticoagulants' },
    { keywords: ['statine', 'atorvastatine', 'rosuvastatine'], target: 'Hypolipidémiants' },
    { keywords: ['antidiabétique', 'antidiabetique', 'metformine'], target: 'Antidiabétiques' },
    { keywords: ['insuline'], target: 'Antidiabétiques' },
    { keywords: ['nitroglycérine', 'nitro', 'nitrates'], target: 'Nitroglycérine (Nitro)' },
    { keywords: ['morphine', 'opioïde', 'opioide'], target: 'Morphine' },
    { keywords: ['antibiotique'], target: 'Antibiotiques' },
    { keywords: ['lévodopa', 'levodopa', 'sinemet'], target: 'Sinemet' },
    { keywords: ['antialzheimer', 'donépézil', 'donepezil', 'aricept'], target: 'Donépézil' },
    { keywords: ['galantamine', 'reminyl'], target: 'Galantamine' },
    { keywords: ['mémantine', 'memantine', 'ebixa'], target: 'Mémantine' },
    { keywords: ['rivastigmine', 'exelon'], target: 'Rivastigmine' },
    { keywords: ['anti-obésité', 'anti-obesite'], target: 'Agents anti-obésité' },
    { keywords: ['bupropion', 'wellbutrin', 'zyban', 'contrave'], target: 'Bupropion (Wellbutrin, Zyban, Contrave)' },
    { keywords: ['liraglutide', 'saxenda', 'victoza'], target: 'Liraglutide' },
    { keywords: ['orlistat', 'xenical'], target: 'Orlistat' },
    { keywords: ['impuissance', 'érectile', 'dysfonctionnement érectile'], target: "Traitement de l'impuissance" },
    { keywords: ['céphalée', 'migraine', 'horton'], target: 'Traitement des céphalées vasculaires' },
    { keywords: ['almotriptan', 'axert'], target: 'Almotriptan' },
    { keywords: ['élétriptan', 'eletriptan', 'relpax'], target: 'Élétriptan' },
    { keywords: ['frovatriptan', 'frova'], target: 'Frovatriptan' },
    { keywords: ['naratriptan', 'amerge'], target: 'Naratriptan' },
    { keywords: ['rizatriptan', 'maxalt'], target: 'Rizatriptan' },
    { keywords: ['sumatriptan', 'imitrex', 'onzetra'], target: 'Sumatriptan' },
    { keywords: ['zolmitriptan', 'zomig'], target: 'Zolmitriptan' },
    { keywords: ['dihydroergotamine', 'dhe', 'migranal'], target: 'Dihydroergotamine' },
    { keywords: ['butalbital', 'fiorinal', 'tecnal', 'trianal'], target: 'Butalbital (Composés)' },
    { keywords: ['grossesse', 'allaitement', 'accouchement', 'travail'], target: 'Grossesse et allaitement' },
    { keywords: ['dinoprostone', 'cervidil', 'prepidil'], target: 'Dinoprostone' },
    { keywords: ['ergonovine', 'ergométrine'], target: 'Ergonovine' },
    { keywords: ['oxytocine', 'pitocin', 'syntocinon'], target: 'Oxytocine' },
    { keywords: ['immunoglobuline rh', 'rogam', 'winrho'], target: 'Immunoglobuline Rho (D)' },
    { keywords: ['sildénafil', 'sildenafil', 'viagra'], target: 'Sildénafil' },
    { keywords: ['tadalafil', 'cialis'], target: 'Tadalafil' },
    { keywords: ['vardénafil', 'vardenafil', 'levitra'], target: 'Vardénafil' },

    // === PATHOLOGIES ===
    // Cardiovasculaire
    { keywords: ['insuffisance cardiaque'], target: 'Insuffisance Cardiaque' },
    { keywords: ['infarctus', 'sca', 'stemi', 'nstemi'], target: 'Infarctus du Myocarde' },
    { keywords: ['angine stable'], target: 'Angine Stable' },
    { keywords: ['angine instable'], target: 'Angine Instable' },
    { keywords: ['mcas', 'maladie coronarienne'], target: 'MCAS' },
    { keywords: ['coronaropathie'], target: 'Coronaropathie' },
    { keywords: ['hta', 'hypertension'], target: 'HTA (Hypertension Artérielle)' },
    { keywords: ['fibrillation auriculaire', 'fa'], target: 'Fibrillation Auriculaire' },
    { keywords: ['map', 'maladie artérielle périphérique'], target: 'MAP (Maladie Artérielle Périphérique)' },
    { keywords: ['tvp', 'thrombose veineuse profonde', 'phlébite'], target: 'TVP (Thrombose Veineuse Profonde)' },
    { keywords: ['ascite'], target: 'Ascite' },
    { keywords: ['insuffisance veineuse', 'ivc'], target: 'IVC & Ulcères Veineux' },
    { keywords: ['varice'], target: 'Varices' },
    { keywords: ['choc cardiogénique'], target: 'Choc Cardiogénique' },

    // Respiratoire
    { keywords: ['pneumonie'], target: 'Pneumonie' },
    { keywords: ['mpoc', 'emphysème', 'bronchite chronique'], target: 'MPOC' },
    { keywords: ['asthme'], target: 'Asthme' },
    { keywords: ['oap', 'oedème aigu du poumon'], target: 'OAP (Oedème Aigu du Poumon)' },
    { keywords: ['bronchiolite', 'vrs'], target: 'Bronchiolite' },
    { keywords: ['cancer du poumon'], target: 'Cancer du Poumon' },
    { keywords: ['acidose respiratoire'], target: 'Acidose Respiratoire' },
    { keywords: ['alcalose respiratoire'], target: 'Alcalose Respiratoire' },

    // Nerveux
    { keywords: ['avc', 'accident vasculaire cérébral'], target: 'AVC (Accident Vasculaire Cérébral)' },
    { keywords: ['alzheimer'], target: 'Maladie d\'Alzheimer' },
    { keywords: ['parkinson'], target: 'Maladie de Parkinson' },
    { keywords: ['sep', 'sclérose en plaques'], target: 'Sclérose en Plaques (SEP)' },
    { keywords: ['sla', 'charcot', 'sclérose latérale amyotrophique'], target: 'Sclérose Latérale Amyotrophique (SLA)' },
    { keywords: ['delirium', 'confusion'], target: 'Délirium' },
    { keywords: ['tcc', 'traumatisme crânio-cérébral'], target: 'TCC (Traumatisme Crânio-Cérébral)' },
    { keywords: ['méningite', 'meningite'], target: 'Méningite' },

    // Gastro-intestinal
    { keywords: ['cirrhose'], target: 'Cirrhose' },
    { keywords: ['pancréatite', 'pancreatite'], target: 'Pancréatite Aiguë' },
    { keywords: ['mici', 'crohn', 'colite'], target: 'Maladies Inflammatoires Chroniques de l\'Intestin (MICI)' },
    { keywords: ['occlusion intestinale', 'iléus'], target: 'Occlusion Intestinale' },
    { keywords: ['cancer colorectal'], target: 'Cancer Colorectal' },
    { keywords: ['cholécystite', 'cholecystite'], target: 'Cholécystite' },
    { keywords: ['péritonite', 'peritonite'], target: 'Péritonite' },

    // Endocrinien
    { keywords: ['diabète type 1', 'diabete type 1'], target: 'Diabète de Type 1' },
    { keywords: ['diabète type 2', 'diabete type 2'], target: 'Diabète de Type 2' },
    { keywords: ['hypoglycémie', 'hypoglycemie'], target: 'Hypoglycémie (Complication Diabète)' },
    { keywords: ['acidocétose', 'acidocetose', 'acd'], target: 'Acidocétose Diabétique (ACD)' },
    { keywords: ['choc hyperosmolaire', 'shh'], target: 'Syndrome Hyperglycémique Hyperosmolaire (SHH)' },
    { keywords: ['hypothyroïdie', 'hypothyroidie'], target: 'Hypothyroïdie' },
    { keywords: ['hyperthyroïdie', 'hyperthyroidie'], target: 'Hyperthyroïdie' },
    { keywords: ['obésité', 'obesite', 'imc'], target: 'Obésité' },
    { keywords: ['syndrome métabolique'], target: 'Syndrome Métabolique' },

    // Urinaire
    { keywords: ['infection urinaire', 'cystite', 'pyélonéphrite'], target: 'Infection Urinaire' },
    { keywords: ['ira', 'insuffisance rénale aiguë'], target: 'Insuffisance Rénale Aiguë (IRA)' },
    { keywords: ['irc', 'insuffisance rénale chronique'], target: 'Insuffisance Rénale Chronique (IRC)' },
    { keywords: ['incontinence urinaire'], target: 'Incontinence Urinaire' },

    // Reproducteur
    { keywords: ['itss'], target: 'ITSS (Infections Transmissibles Sexuellement et par le Sang)' },
    { keywords: ['chlamydia'], target: 'Chlamydia' },
    { keywords: ['gonorrhée', 'gonorrhee'], target: 'Gonorrhée' },
    { keywords: ['syphilis'], target: 'Syphilis' },
    { keywords: ['vph', 'papillome'], target: 'VPH (Virus du Papillome Humain)' },
    { keywords: ['herpès génital', 'herpes genital'], target: 'Herpès Génital' },
    { keywords: ['endométriose', 'fibrome', 'kyste'], target: 'Troubles Bénins (Féminin)' },
    { keywords: ['cancer du col'], target: 'Cancer du Col de l\'Utérus' },
    { keywords: ['cancer de l\'utérus', 'endomètre'], target: 'Cancer de l\'Utérus (Endomètre)' },
    { keywords: ['cancer de l\'ovaire'], target: 'Cancer de l\'Ovaire' },
    { keywords: ['cancer du sein'], target: 'Cancer du Sein' },
    { keywords: ['hbp', 'prostate', 'hyperplasie'], target: 'Hyperplasie Bénigne de la Prostate (HBP)' },
    { keywords: ['cancer de la prostate'], target: 'Cancer de la Prostate' },

    // Multisystémique & Chocs
    { keywords: ['cancer', 'chimio', 'tumeur'], target: 'Cancer (Généralités)' },
    { keywords: ['choc septique', 'sepsis'], target: 'Choc Septique' },
    { keywords: ['choc hypovolémique'], target: 'Choc Hypovolémique' },
    { keywords: ['choc anaphylactique', 'allergie'], target: 'Choc Anaphylactique' },
    { keywords: ['choc neurogénique'], target: 'Choc Neurogénique' },
    { keywords: ['choc obstructif'], target: 'Choc Obstructif' },
    { keywords: ['infection nosocomiale', 'sarm', 'erv'], target: 'Infections Nosocomiales' },
    { keywords: ['maladies infectieuses'], target: 'Maladies Infectieuses' },
    { keywords: ['vih', 'sida'], target: 'VIH (Virus de l\'Immunodéficience Humaine)' },
    { keywords: ['fibrose kystique', 'mucoviscidose'], target: 'Fibrose Kystique (Mucoviscidose)' },
    { keywords: ['croissance', 'retard de croissance'], target: 'Altération de la croissance' },
    { keywords: ['acidose métabolique'], target: 'Acidose Métabolique' },
    { keywords: ['alcalose métabolique'], target: 'Alcalose Métabolique' },

    // Tégumentaire & Musculosquelettique
    { keywords: ['escarre', 'lésion de pression'], target: 'Lésion de pression (Escarre)' },
    { keywords: ['cancer cutané', 'mélanome'], target: 'Cancer cutané' },
    { keywords: ['fracture sans déplacement'], target: 'Fracture sans déplacement' },
    { keywords: ['fracture avec déplacement', 'compartiment'], target: 'Fracture avec déplacement ou écrasement' },
    { keywords: ['fracture de la hanche'], target: 'Fracture de la hanche' },
    { keywords: ['arthrose de la hanche', 'coxarthrose'], target: 'Arthrose de la hanche (Coxarthrose)' },
    { keywords: ['arthrose du genou', 'gonarthrose'], target: 'Arthrose du genou (Gonarthrose)' },

    // === INTERVENTIONS & EXAMENS ===
    { keywords: ['angioplastie', 'stent'], target: 'Angioplastie Coronarienne' },
    { keywords: ['pontage', 'pac'], target: 'Pontage Aortocoronarien (PAC)' },
    { keywords: ['thrombectomie'], target: 'Thrombectomie Mécanique' },
    { keywords: ['pth', 'prothèse de hanche'], target: 'Prothèse Totale de Hanche (PTH)' },
    { keywords: ['ptg', 'prothèse de genou'], target: 'Prothèse Totale de Genou (PTG)' },
    { keywords: ['lobectomie', 'pneumonectomie'], target: 'Lobectomie / Pneumonectomie' },
    { keywords: ['cataracte'], target: 'Chirurgie de la Cataracte' },
    { keywords: ['pacemaker', 'stimulateur cardiaque'], target: 'Pose de Pacemaker' },
    { keywords: ['trachéotomie'], target: 'Trachéotomie' },
    { keywords: ['hystérectomie'], target: 'Hystérectomie' },
    { keywords: ['mastectomie'], target: 'Mastectomie Radicale Modifiée' },
    { keywords: ['tumorectomie'], target: 'Tumorectomie (Sein)' },
    { keywords: ['turp', 'résection prostate'], target: 'Résection Transurétrale de la Prostate (TURP)' },
    { keywords: ['ecg', 'électrocardiogramme'], target: 'ECG (Électrocardiogramme)' },
    { keywords: ['troponine', 'ck-mb'], target: 'Troponines & CK-MB' },
    { keywords: ['bilan lipidique', 'lipidogramme'], target: 'Lipidogramme' },
    { keywords: ['scanner cérébral', 'tdm cérébral'], target: 'Scanner (TDM) Cérébral' },
    { keywords: ['bilan hépatique', 'asat', 'alat'], target: 'Bilan Hépatique (ASAT/ALAT)' },
    { keywords: ['inr', 'tca', 'coagulation'], target: 'Bilan de Coagulation (INR / TCA)' },
    { keywords: ['créatinine', 'creatinine', 'urée'], target: 'Créatinine & Urée' },
    { keywords: ['hba1c'], target: 'HbA1c (Hémoglobine Glyquée)' },
    { keywords: ['gsa', 'gaz sanguins'], target: 'Gaz Sanguins Artériels (GSA)' },
    { keywords: ['glasgow', 'gcs'], target: 'Échelle de Glasgow (GCS)' },
    { keywords: ['mmse', 'moca'], target: 'Évaluation Cognitive (MMSE/MoCA)' },
    { keywords: ['apgar'], target: 'Score d\'Apgar' }
];
